(define (problem imv-p04-curator-drone-seismic)
  (:domain imv-seismic)
  (:requirements :timed-initial-literals)
  (:objects
    entrance tunnel hallA cryo pod1 pod2 stasis - other-site
    a1 a2 b1 b2 cs1 cs2 - artifact
    r1 d1 - robot
    slot1 slot2 slot_d - slot
    vs - vunit
  )
  (:init
    (hall_b_safe)
    (at r1 entrance)
    (at d1 entrance)
    (manip_free r1)
    (manip_free d1)
    (sealing_off vs)
    (tunnel tunnel)
    (non_tunnel entrance)
    (non_tunnel hallA)
    (non_tunnel hallB)
    (non_tunnel cryo)
    (non_tunnel pod1)
    (non_tunnel pod2)
    (non_tunnel stasis)
    (robot_slot r1 slot1)
    (robot_slot r1 slot2)
    (robot_slot d1 slot_d)
    (slot_free r1 slot1)
    (slot_free r1 slot2)
    (slot_free d1 slot_d)

    (artifact_at a1 hallA)
    (artifact_at a2 hallA)
    (artifact_at b1 hallB)
    (artifact_at b2 hallB)
    (artifact_at cs1 cryo)
    (artifact_at cs2 cryo)

    (connected entrance tunnel)
    (connected tunnel entrance)
    (connected tunnel cryo)
    (connected cryo tunnel)
    (connected tunnel pod1)
    (connected pod1 tunnel)
    (connected tunnel pod2)
    (connected pod2 tunnel)
    (connected tunnel hallA)
    (connected hallA tunnel)
    (connected tunnel hallB)
    (connected hallB tunnel)
    (connected tunnel stasis)
    (connected stasis tunnel)

    ; Same alternating windows as problem-seismic.pddl
    (at 20.0 (not (hall_b_safe)))
    (at 50.0 (hall_b_safe))
    (at 80.0 (not (hall_b_safe)))
    (at 110.0 (hall_b_safe))
  )
  (:goal (and
    (artifact_at a1 cryo)
    (artifact_at a2 cryo)
    (artifact_at b1 pod1)
    (artifact_at b2 pod2)
    (artifact_at cs1 stasis)
    (artifact_at cs2 stasis)
  ))
  (:metric minimize (total-time))
)
